/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class UartTest */

#ifndef _Included_UartTest
#define _Included_UartTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     UartTest
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_UartTest_sayHello
  (JNIEnv *, jclass);

/*
 * Class:     UartTest
 * Method:    openUart
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_UartTest_openUart
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     UartTest
 * Method:    closeUart
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_UartTest_closeUart
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
